= Tailor metrics

Firstly, let's add the micrometer extension to our setup.
Please open a new terminal window, and make sure you’re at the root of your tutorial-app project, then run:

[.console-input]
[source,bash]
----
./mvnw quarkus:add-extension -Dextensions="io.quarkus:quarkus-micrometer,quarkus-micrometer-registry-prometheus"
----

== Configuration of common tags

When deploying accross multiple projects/namespaces is always good to have an unified view over some application metrics.
Let's define several common tags for the application, varying in value at deployment time:

[.console-input]
[source,java]
----
package com.redhat.developers;

import io.smallrye.config.ConfigMapping;

@ConfigMapping(prefix = "global") <1>
interface GlobalTagsConfig {
     String PROFILE = "profile";
     String REGION = "region";
     String COUNTRY="country";

     String region();
     String country();
}
----

`@ConfigMapping(prefix = "global")` annotation maps configurations from `application.properties` prefixed by `global`:

[.console-input]
[source,properties]
----
global.region=${REGION:CEE} <1>
global.country=${COUNTRY:'Romania'}
----

<1> Environment configuration will be named `REGION` and having the default value `CEE`.

Further, we will propagate these configurations by via `MeterFilter` customization:

[.console-input]
[source,java]
----
package com.redhat.developers;

import io.micrometer.core.instrument.Tag;
import io.micrometer.core.instrument.config.MeterFilter;
import io.quarkus.runtime.configuration.ProfileManager;

import javax.enterprise.inject.Produces;
import javax.inject.Inject;
import javax.inject.Singleton;
import java.util.Arrays;

@Singleton
public class CustomConfiguration {

    @Inject
    GlobalTagsConfig tagsConfig;

    @Produces
    @Singleton
    public MeterFilter configureTagsForAll() {
        return MeterFilter.commonTags(Arrays.asList(
           Tag.of(GlobalTagsConfig.REGION, tagsConfig.region()),
           Tag.of(GlobalTagsConfig.COUNTRY, tagsConfig.country()),
           Tag.of(GlobalTagsConfig.PROFILE, ProfileManager.getActiveProfile())
        ));
    }

}
----

== Metrics definition at endpoint level

When looking to improve the performance of certain application features, is useful to have metrics defined at endpoint level as well.
Let's modify `GreetingResource` with the following:

[.console-input]
[source,java]
----
package com.redhat.developers;

import io.micrometer.core.annotation.Counted;
import io.micrometer.core.annotation.Timed;

import javax.transaction.Transactional;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import java.util.List;

@Path("messages")
public class GreetingResource {

    public static final String URI = "uri";
    public static final String API_GREET = "api.greet";

    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @Transactional
    @Timed(value = "greetings.creation", longTask = true, extraTags = {URI, API_GREET}) <1>
    public Message create(Message message) {
        Message.persist(message);
        return message;
    }

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Counted(value = "http.get.requests", extraTags = {URI, API_GREET}) <2>
    public List<Message> findAll() {
        return Message.findAll().list();
    }

}
----

<1> Measure expected long running requests with `@Timed` annotation.
<2> Count the creation of resources with `@Counted` annotation.

== Inspect the custom metrics

Start the application in DevMode:

[.console-input]
[source,bash]
----
mvn quarkus:dev
----

and curl a couple of times the `/messages` endpoint:
[.console-input]
[source,bash]
----
curl localhost:8080/messages
----

You can see your custom metrics recorded at http://localhost:8080/q/metrics :

[.console-input]
[source,properties]
----
jvm_memory_max_bytes{area="heap",country="'Romania'",id="Survivor Space",profile="prod",region="CEE",} 4390912.0
jvm_memory_max_bytes{area="heap",country="'Romania'",id="Eden Space",profile="prod",region="CEE",} 3.5258368E7
jvm_memory_max_bytes{area="heap",country="'Romania'",id="Tenured Gen",profile="prod",region="CEE",} 8.8080384E7
jvm_memory_max_bytes{area="nonheap",country="'Romania'",id="CodeHeap 'profiled nmethods'",profile="prod",region="CEE",} 1.22912768E8
jvm_memory_max_bytes{area="nonheap",country="'Romania'",id="Compressed Class Space",profile="prod",region="CEE",} 1.073741824E9
jvm_memory_max_bytes{area="nonheap",country="'Romania'",id="Metaspace",profile="prod",region="CEE",} -1.0
jvm_memory_max_bytes{area="nonheap",country="'Romania'",id="CodeHeap 'non-nmethods'",profile="prod",region="CEE",} 5828608.0
jvm_memory_max_bytes{area="nonheap",country="'Romania'",id="CodeHeap 'non-profiled nmethods'",profile="prod",region="CEE",} 1.22916864E8
# HELP http_get_requests_total
# TYPE http_get_requests_total counter
http_get_requests_total{class="com.redhat.developers.GreetingResource",country="'Romania'",exception="none",method="findAll",profile="prod",region="CEE",result="success",uri="api.greet",} 3.0
----

== Deploy to OpenShift

You can deploy your latest code changes by using the command:

[.console-input]
[source,bash]
----
mvn clean package -Dquarkus.kubernetes.deploy=true -Dquarkus.container-image.push=true
----

However, we should externalize the configuration to OpenShift resources.
Firstly, let's create a configmap:

[.console-input]
[source,bash]
----
oc create cm country-nl --from-literal=region=Europe --from-literal=country=Netherlands
----

And we can append this new resource to our existing deployment:

[.console-input]
[source,bash]
----
oc set env --from=configmap/country-nl dc/greeting-app
----

Rollout the latest `DeploymentConfig` using:
[.console-input]
[source,bash]
----
oc rollout latest dc/greeting-app
----

You can now check your overwritten metrics via:

[.console-input]
[source,bash]
----
curl $ROUTE_URL/q/metrics
----

