[tabs]
====
JVM mode::
+
--
[#basics-build-quarkus-jvm-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
./mvnw package
----

To run the application in jvm mode

[#basics-build-run-jvm-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
java -jar target/quarkus-app/quarkus-run.jar
----

--
Native mode::
+
--
[#basics-build-quarkus-native-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
./mvnw -DskipTests clean package -Pnative
----

NOTE: Native compilation will take few minutes to complete.

To run the application in native mode

[#basics-build-run-native-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
./target/tutorial-app-1.0-SNAPSHOT-runner
----

--
Native container-build mode::
+
--
[#basics-build-quarkus-native-docker-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
./mvnw package -DskipTests -Pnative -Dquarkus.native.container-build=true
----

NOTE: Native compilation will take few minutes to complete.

To run the application in native mode you need to build a Docker image using the native file generated in previous step:

[#basics-build-run-native-docker-app]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
docker build -f src/main/docker/Dockerfile.native -t example/tutorial-app:1.0-SNAPSHOT .
docker run -it --rm -p 8080:8080 example/tutorial-app:1.0-SNAPSHOT
----

--
====

You'll see an output like this one:

[.console-output]
[source,text]
----
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2026-09-21 14:10:35,627 INFO  [io.quarkus] (main) tutorial-app 1.0-SNAPSHOT on JVM (powered by Quarkus 3.39.4) started in 0.884s. Listening on: http://0.0.0.0:8080
2026-09-21 14:10:35,631 INFO  [io.quarkus] (main) Profile prod activated.
2026-09-21 14:10:35,631 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-postgresql, kubernetes, narayana-jta, rest, rest-jsonb, smallrye-context-propagation, smallrye-openapi, vertx]
----

[NOTE]
====
Quarkus 3 prints `on JVM` next to the version, and the `Installed features` list grows as you add
extensions in the later chapters.

There is no entity in the project yet, so Hibernate ORM stays inactive and the application starts
without a database. From the xref:configuration.adoc[Configuration] chapter onwards, running the
packaged application in `prod` mode needs a reachable PostgreSQL instance.
====